In [42]:
import glob

import pandas as pd
import dask.dataframe as dd

In [43]:
def read_data(location, format, frac=0.02):
    files = glob.glob(f"{location}*.{format}")
    if format == "parquet":
        data = dd.read_parquet(location).sample(frac=0.02)
    # elif format == "h5":
    #     data = dd.concat([read_hdf5(file) for file in files]).sample(frac=0.02)
    data = data.rename(columns={"Distance to CIS": "Distance to CSL"})
    return data

In [44]:
# ddf = read_data("../data/aggregated_data/parquet/", "parquet", frac=1)
# ddf

In [45]:
pd.set_option('display.max_columns', None)
# ddf = dd.read_parquet("../data/aggregated_data/parquet/tickets_full_merge_2024.parquet")
ddf = dd.read_parquet([
    "../data/aggregated_data/parquet/tickets_full_merge_2023.parquet",
    "../data/aggregated_data/parquet/tickets_full_merge_2024.parquet",
])
ddf.dropna(subset=["tempmax", "tempmin", "temp",  "conditions", "humidity", "windspeed", "visibility"])
ddf.head(5)

Summons Number Plate ID Registration State Plate Type     Issue Date  \
0      1484699750  GCX5397                 NY        PAS  1687132800000   
1      1484721329  HEZ7860                 NY        PAS  1656892800000   
2      1484721330  HDE5505                 NY        PAS  1656892800000   
3      1484724136  JEB6269                 NY        PAS  1656892800000   
4      1484725888  KET8159                 NY        PAS  1657324800000   

   Violation Code Vehicle Body Type Vehicle Make Issuing Agency  Street Code1  \
0              63              SUBN        CHEVR              N         30640   
1              20              SUBN        SUBAR              K         39202   
2              20              SUBN        ME/BE              K         39202   
3              68               SDN        CHEVR              N         22278   
4              20               SDN        CHEVR              K         42850   

   Street Code2  Street Code3  Vehicle Expiration Date  Violation Location  \
0         13015         28540                 20230103                   1   
1             0             0                 20240305                 122   
2             0             0                 20240303                 122   
3             0             0                 20221018                 122   
4         33720         61830                 20221029                  84   

   Violation Precinct  Issuer Precinct  Issuer Code Issuer Command  \
0                   1                1       161331           0001   
1                 122                5       160548           0005   
2                 122                5       160548           0005   
3                 122                5       160690           0005   
4                  84                4       160448           0004   

  Issuer Squad Violation Time Violation County  \
0         0000          1102A        Manhattan   
1         0000          0235P    Staten Island   
2         0000          0156P    Staten Island   
3         0000          0626P    Staten Island   
4         0000          0841P         Brooklyn   

  Violation In Front Of Or Opposite House Number        Street Name  \
0                                 O          109           SOUTH ST   
1                                                     MIDLAND BEACH   
2                                                     MIDLAND BEACH   
3                                                 CEDAR GROVE BEACH   
4                                 F           60          FURMAN ST   

  Intersecting Street  Date First Observed  Law Section Sub Division  \
0                                        0          408           F3   
1               LOT 8                    0          408           C4   
2               LOT 8                    0          408            D   
3         PARKING LOT                    0          408           F3   
4                                        0          408           C4   

  Violation Legal Code Days Parking In Effect From Hours In Effect  \
0                                     BBBBBBB                  ALL   
1                                     BBBBBBB                  ALL   
2                                     BBBBBBB                  ALL   
3                                     BBBBBBB                  ALL   
4                                     BBBBBBB                  ALL   

  To Hours In Effect Vehicle Color  Vehicle Year  Feet From Curb  \
0                ALL           WHT          2010               0   
1                ALL            GL          2016               0   
2                ALL         WHITE          2019               0   
3                ALL         SILVE          2015               0   
4                ALL         SILVE          2011               0   

  Violation Post Code Violation Description   Latitude  Longitude  \
0                                            40.708622 -74.003870   
1                                            4

In [46]:
def chunk(s):
    # for the comments, assume only a single grouping column, the 
    # implementation can handle multiple group columns.
    #
    # s is a grouped series. value_counts creates a multi-series like 
    # (group, value): count
    return s.value_counts()


def agg(s):
    # s is a grouped multi-index series. In .apply the full sub-df will passed
    # multi-index and all. Group on the value level and sum the counts. The
    # result of the lambda function is a series. Therefore, the result of the 
    # apply is a multi-index series like (group, value): count
    return s.apply(lambda s: s.groupby(level=-1, sort=False).sum())

    # # faster version using pandas internals
    # s = s._selected_obj
    # return s.groupby(level=list(range(s.index.nlevels))).sum()


def finalize(s):
    # s is a multi-index series of the form (group, value): count. First
    # manually group on the group part of the index. The lambda will receive a
    # sub-series with multi index. Next, drop the group part from the index.
    # Finally, determine the index with the maximum value, i.e., the mode.
    level = list(range(s.index.nlevels - 1))
    return (
        s.groupby(level=level, sort=False)
        # .apply(lambda s: s.reset_index(level=level, drop=True).argmax())
        .apply(lambda s: s.reset_index(level=level, drop=True).idxmax())
    )


mode = dd.Aggregation('mode', chunk, agg, finalize)

In [47]:
daily_ddf = ddf.groupby("Issue Date").agg({
    "tempmax": "first", 
    "tempmin": "first", 
    "temp": "first", 
    "conditions": "first", 
    "humidity": "first", 
    "windspeed": "first", 
    "visibility": "first",
    "Distance to CMS": "mean",
    "Distance to CHS": "mean",
    "Distance to CIL": "mean",
    "Distance to CIS": "mean",
    "Distance to CB": "mean",
})

daily_ddf["count"] = ddf.groupby("Issue Date").size()
daily_ddf = daily_ddf.dropna()
daily_ddf.compute()

tempmax  tempmin  temp              conditions  humidity  \
Issue Date                                                                
1687132800000     25.7     19.3  21.8                   Clear      64.5   
1656892800000     29.4     19.9  25.0                    Rain      42.2   
1657324800000     29.3     22.8  25.1  Rain, Partially cloudy      61.5   
1656806400000     31.0     24.3  26.8        Partially cloudy      52.4   
1656720000000     31.1     24.3  27.3  Rain, Partially cloudy      66.9   
...                ...      ...   ...                     ...       ...   
1716854400000     26.7     18.9  22.5        Partially cloudy      64.1   
1716336000000     27.9     18.0  23.1                   Clear      63.2   
1715904000000     21.7     15.6  18.2  Rain, Partially cloudy      66.5   
1716422400000     25.6     20.0  22.3                    Rain      70.8   
1716508800000     29.3     19.4  24.2                   Clear      52.4   

               windspeed  visibility  Distance to CMS  Distance to CHS  \
Issue Date                                                               
1687132800000       21.5        15.9         0.622759         0.706088   
1656892800000       14.0        15.7         0.628087         0.738772   
1657324800000       21.6        15.9         0.616593         0.707777   
1656806400000       21.5        16.0         0.643300         0.767375   
1656720000000       16.2        16.0         0.594962         0.685915   
...                  ...         ...              ...              ...   
1716854400000       35.7        15.9         0.600562         0.663457   
1716336000000       14.9        16.0         0.622040         0.704169   
1715904000000       27.3        15.8         0.598306         0.665789   
1716422400000       24.1        15.4         0.594586         0.686704   
1716508800000       14.6        16.0         0.597741         0.669072   

               Distance to CIL  Distance to CIS  Distance to CB  count  
Issue Date                                                              
1687132800000         0.549993         4.631736        0.108002  12192  
1656892800000         0.705272         5.421443        0.128032   3059  
1657324800000         0.602161         4.856251        0.106574  12824  
1656806400000         0.632290         4.617807        0.132466   5147  
1656720000000         0.568028         4.771755        0.096920  17168  
...                        ...              ...             ...    ...  
1716854400000         0.534219         4.424932        0.110785  28672  
1716336000000         0.578194         4.671199        0.111999  27157  
1715904000000         0.528128         4.282436        0.109453  29689  
1716422400000         0.572924         4.572234        0.111724  28503  
1716508800000         0.525205         4.343023        0.107791  27736  

[695 rows x 13 columns]

In [48]:
daily_ddf["High Number of Tickets"] = (daily_ddf["count"] > 20000).astype(int)
daily_ddf.compute()

tempmax  tempmin  temp              conditions  humidity  \
Issue Date                                                                
1687132800000     25.7     19.3  21.8                   Clear      64.5   
1656892800000     29.4     19.9  25.0                    Rain      42.2   
1657324800000     29.3     22.8  25.1  Rain, Partially cloudy      61.5   
1656806400000     31.0     24.3  26.8        Partially cloudy      52.4   
1656720000000     31.1     24.3  27.3  Rain, Partially cloudy      66.9   
...                ...      ...   ...                     ...       ...   
1716854400000     26.7     18.9  22.5        Partially cloudy      64.1   
1716336000000     27.9     18.0  23.1                   Clear      63.2   
1715904000000     21.7     15.6  18.2  Rain, Partially cloudy      66.5   
1716422400000     25.6     20.0  22.3                    Rain      70.8   
1716508800000     29.3     19.4  24.2                   Clear      52.4   

               windspeed  visibility  Distance to CMS  Distance to CHS  \
Issue Date                                                               
1687132800000       21.5        15.9         0.622759         0.706088   
1656892800000       14.0        15.7         0.628087         0.738772   
1657324800000       21.6        15.9         0.616593         0.707777   
1656806400000       21.5        16.0         0.643300         0.767375   
1656720000000       16.2        16.0         0.594962         0.685915   
...                  ...         ...              ...              ...   
1716854400000       35.7        15.9         0.600562         0.663457   
1716336000000       14.9        16.0         0.622040         0.704169   
1715904000000       27.3        15.8         0.598306         0.665789   
1716422400000       24.1        15.4         0.594586         0.686704   
1716508800000       14.6        16.0         0.597741         0.669072   

               Distance to CIL  Distance to CIS  Distance to CB  count  \
Issue Date                                                               
1687132800000         0.549993         4.631736        0.108002  12192   
1656892800000         0.705272         5.421443        0.128032   3059   
1657324800000         0.602161         4.856251        0.106574  12824   
1656806400000         0.632290         4.617807        0.132466   5147   
1656720000000         0.568028         4.771755        0.096920  17168   
...                        ...              ...             ...    ...   
1716854400000         0.534219         4.424932        0.110785  28672   
1716336000000         0.578194         4.671199        0.111999  27157   
1715904000000         0.528128         4.282436        0.109453  29689   
1716422400000         0.572924         4.572234        0.111724  28503   
1716508800000         0.525205         4.343023        0.107791  27736   

               High Number of Tickets  
Issue Date                             
1687132800000                       0  
1656892800000                       0  
1657324800000                       0  
1656806400000                       0  
1656720000000                       0  
...                               ...  
1716854400000                       1  
1716336000000                       1  
1715904000000                       1  
1716422400000                       1  
1716508800000                       1  

[695 rows x 14 columns]

In [49]:
daily_mode_ddf = ddf.groupby("Issue Date", sort=False).agg({
    "Registration State": mode,
    "Plate Type": mode,
    "Violation Code": mode,
    "Vehicle Body Type": mode,
    "Vehicle Make": mode,
    "Issuing Agency": mode,
    "Violation County": mode,
})
daily_mode_ddf.compute()

c:\Users\Luka\miniconda3\envs\BD_project\lib\site-packages\dask\dataframe\groupby.py:1145: RuntimeWarning: The values in the array are unorderable. Pass `sort=False` to suppress this warning.
  return df.__class__(result)
c:\Users\Luka\miniconda3\envs\BD_project\lib\site-packages\dask\dataframe\groupby.py:1145: RuntimeWarning: The values in the array are unorderable. Pass `sort=False` to suppress this warning.
  return df.__class__(result)


Registration State Plate Type  Violation Code Vehicle Body Type  \
Issue Date                                                                      
1656720000000                 NY        PAS              38              SUBN   
1656806400000                 NY        PAS              14              SUBN   
1656892800000                 NY        PAS              71              SUBN   
1656979200000                 NY        PAS              21              SUBN   
1657065600000                 NY        PAS              38              SUBN   
...                          ...        ...             ...               ...   
1719273600000                 NY        PAS              68              SUBN   
1719360000000                 NY        COM              98                     
1719446400000                 NY        OMT              14              TAXI   
1719532800000                 NY        PAS              63              SUBN   
1719619200000                 NY        PAS              98               SDN   

              Vehicle Make Issuing Agency Violation County  
Issue Date                                                  
1656720000000        HONDA              T        Manhattan  
1656806400000        HONDA              T        Manhattan  
1656892800000        HONDA              T        Manhattan  
1656979200000        HONDA              T        Manhattan  
1657065600000         FORD              T        Manhattan  
...                    ...            ...              ...  
1719273600000         FORD              U           Queens  
1719360000000        ISUZU              P         Brooklyn  
1719446400000        TOYOT              M        Manhattan  
1719532800000         FORD              K           Queens  
1719619200000         JEEP              P         Brooklyn  

[723 rows x 7 columns]

In [50]:
daily_ddf = daily_ddf.merge(daily_mode_ddf, on="Issue Date")
daily_ddf.compute()

c:\Users\Luka\miniconda3\envs\BD_project\lib\site-packages\dask\dataframe\groupby.py:1145: RuntimeWarning: The values in the array are unorderable. Pass `sort=False` to suppress this warning.
  return df.__class__(result)
c:\Users\Luka\miniconda3\envs\BD_project\lib\site-packages\dask\dataframe\groupby.py:1145: RuntimeWarning: The values in the array are unorderable. Pass `sort=False` to suppress this warning.
  return df.__class__(result)
c:\Users\Luka\miniconda3\envs\BD_project\lib\site-packages\dask\dataframe\groupby.py:1145: RuntimeWarning: The values in the array are unorderable. Pass `sort=False` to suppress this warning.
  return df.__class__(result)
c:\Users\Luka\miniconda3\envs\BD_project\lib\site-packages\dask\dataframe\groupby.py:1145: RuntimeWarning: The values in the array are unorderable. Pass `sort=False` to suppress this warning.
  return df.__class__(result)


tempmax  tempmin  temp              conditions  humidity  \
Issue Date                                                                
1687132800000     25.7     19.3  21.8                   Clear      64.5   
1656892800000     29.4     19.9  25.0                    Rain      42.2   
1657324800000     29.3     22.8  25.1  Rain, Partially cloudy      61.5   
1656806400000     31.0     24.3  26.8        Partially cloudy      52.4   
1656720000000     31.1     24.3  27.3  Rain, Partially cloudy      66.9   
...                ...      ...   ...                     ...       ...   
1716854400000     26.7     18.9  22.5        Partially cloudy      64.1   
1716336000000     27.9     18.0  23.1                   Clear      63.2   
1715904000000     21.7     15.6  18.2  Rain, Partially cloudy      66.5   
1716422400000     25.6     20.0  22.3                    Rain      70.8   
1716508800000     29.3     19.4  24.2                   Clear      52.4   

               windspeed  visibility  Distance to CMS  Distance to CHS  \
Issue Date                                                               
1687132800000       21.5        15.9         0.622759         0.706088   
1656892800000       14.0        15.7         0.628087         0.738772   
1657324800000       21.6        15.9         0.616593         0.707777   
1656806400000       21.5        16.0         0.643300         0.767375   
1656720000000       16.2        16.0         0.594962         0.685915   
...                  ...         ...              ...              ...   
1716854400000       35.7        15.9         0.600562         0.663457   
1716336000000       14.9        16.0         0.622040         0.704169   
1715904000000       27.3        15.8         0.598306         0.665789   
1716422400000       24.1        15.4         0.594586         0.686704   
1716508800000       14.6        16.0         0.597741         0.669072   

               Distance to CIL  Distance to CIS  Distance to CB  count  \
Issue Date                                                               
1687132800000         0.549993         4.631736        0.108002  12192   
1656892800000         0.705272         5.421443        0.128032   3059   
1657324800000         0.602161         4.856251        0.106574  12824   
1656806400000         0.632290         4.617807        0.132466   5147   
1656720000000         0.568028         4.771755        0.096920  17168   
...                        ...              ...             ...    ...   
1716854400000         0.534219         4.424932        0.110785  28672   
1716336000000         0.578194         4.671199        0.111999  27157   
1715904000000         0.528128         4.282436        0.109453  29689   
1716422400000         0.572924         4.572234        0.111724  28503   
1716508800000         0.525205         4.343023        0.107791  27736   

               High Number of Tickets Registration State Plate Type  \
Issue Date                                                            
1687132800000                       0                 NY        PAS   
1656892800000                       0                 NY        PAS   
1657324800000                       0                 NY        PAS   
1656806400000                       0                 NY        PAS   
1656720000000                       0                 NY        PAS   
...                               ...                ...        ...   
1716854400000                       1                 NY        PAS   
1716336000000                       1                 NY        PAS   
1715904000000                       1                 NY        PAS   
1716422400000                       1                 NY        PAS   
1716508800000                       1                 NY        PAS   

               Violation Code Vehicle Body Type Vehicle Make Issuing Agency  \
Issue Date                                                                    
1687132800000              38  

# ML

In [51]:
from dask_ml.model_selection import train_test_split
from dask_ml.preprocessing import Categorizer, OrdinalEncoder
from dask_ml.metrics import mean_squared_error, log_loss, accuracy_score
from sklearn.metrics import log_loss # for some reason dask_ml.metrics.log_loss is not working

In [52]:
ce = Categorizer(columns=["conditions", "Registration State", "Plate Type", "Violation Code", "Vehicle Body Type", "Vehicle Make", "Issuing Agency", "Violation County"])
daily_ddf = ce.fit_transform(daily_ddf)

enc = OrdinalEncoder(columns=["conditions", "Registration State", "Plate Type", "Violation Code", "Vehicle Body Type", "Vehicle Make", "Issuing Agency", "Violation County"])
daily_ddf = enc.fit_transform(daily_ddf)

daily_ddf = daily_ddf.persist()
daily_ddf.compute()

c:\Users\Luka\miniconda3\envs\BD_project\lib\site-packages\dask\dataframe\groupby.py:1145: RuntimeWarning: The values in the array are unorderable. Pass `sort=False` to suppress this warning.
  return df.__class__(result)
c:\Users\Luka\miniconda3\envs\BD_project\lib\site-packages\dask\dataframe\groupby.py:1145: RuntimeWarning: The values in the array are unorderable. Pass `sort=False` to suppress this warning.
  return df.__class__(result)
c:\Users\Luka\miniconda3\envs\BD_project\lib\site-packages\dask\dataframe\groupby.py:1145: RuntimeWarning: The values in the array are unorderable. Pass `sort=False` to suppress this warning.
  return df.__class__(result)
c:\Users\Luka\miniconda3\envs\BD_project\lib\site-packages\dask\dataframe\groupby.py:1145: RuntimeWarning: The values in the array are unorderable. Pass `sort=False` to suppress this warning.
  return df.__class__(result)
c:\Users\Luka\miniconda3\envs\BD_project\lib\site-packages\dask\dataframe\groupby.py:1145: RuntimeWarning: The v

tempmax  tempmin  temp  conditions  humidity  windspeed  \
Issue Date                                                               
1687132800000     25.7     19.3  21.8           0      64.5       21.5   
1656892800000     29.4     19.9  25.0           3      42.2       14.0   
1657324800000     29.3     22.8  25.1           5      61.5       21.6   
1656806400000     31.0     24.3  26.8           2      52.4       21.5   
1656720000000     31.1     24.3  27.3           5      66.9       16.2   
...                ...      ...   ...         ...       ...        ...   
1716854400000     26.7     18.9  22.5           2      64.1       35.7   
1716336000000     27.9     18.0  23.1           0      63.2       14.9   
1715904000000     21.7     15.6  18.2           5      66.5       27.3   
1716422400000     25.6     20.0  22.3           3      70.8       24.1   
1716508800000     29.3     19.4  24.2           0      52.4       14.6   

               visibility  Distance to CMS  Distance to CHS  Distance to CIL  \
Issue Date                                                                     
1687132800000        15.9         0.622759         0.706088         0.549993   
1656892800000        15.7         0.628087         0.738772         0.705272   
1657324800000        15.9         0.616593         0.707777         0.602161   
1656806400000        16.0         0.643300         0.767375         0.632290   
1656720000000        16.0         0.594962         0.685915         0.568028   
...                   ...              ...              ...              ...   
1716854400000        15.9         0.600562         0.663457         0.534219   
1716336000000        16.0         0.622040         0.704169         0.578194   
1715904000000        15.8         0.598306         0.665789         0.528128   
1716422400000        15.4         0.594586         0.686704         0.572924   
1716508800000        16.0         0.597741         0.669072         0.525205   

               Distance to CIS  Distance to CB  count  High Number of Tickets  \
Issue Date                                                                      
1687132800000         4.631736        0.108002  12192                       0   
1656892800000         5.421443        0.128032   3059                       0   
1657324800000         4.856251        0.106574  12824                       0   
1656806400000         4.617807        0.132466   5147                       0   
1656720000000         4.771755        0.096920  17168                       0   
...                        ...             ...    ...                     ...   
1716854400000         4.424932        0.110785  28672                       1   
1716336000000         4.671199        0.111999  27157                       1   
1715904000000         4.282436        0.109453  29689                       1   
1716422400000         4.572234        0.111724  28503                       1   
1716508800000         4.343023        0.107791  27736                       1   

               Registration State  Plate Type  Violation Code  \
Issue Date                                                      
1687132800000                   0           0               3   
1656892800000                   0           0               5   
1657324800000                   0           0               3   
1656806400000                   0           0               0   
1656720000000                   0           0               3   
...                           ...         ...             ...   
1716854400000                   0           0               1   
1716336000000                   0           0               3   
1715904000000                   0           0               1   
1716422400000                   0           0               1   
1716508800000                   0           0               1   

               Vehicle Body Type  Vehicle Make  Issuing Agency  \
Issue Date                                   

In [53]:
X, y = daily_ddf.drop(columns=["count", "High Number of Tickets"]), daily_ddf["High Number of Tickets"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=True, random_state=42)

In [54]:
display(X_train.compute(), y_train.compute())

tempmax  tempmin  temp  conditions  humidity  windspeed  \
Issue Date                                                               
1704153600000      7.7     -0.1   3.5           0      58.7       14.6   
1681084800000     17.9      5.7  11.3           0      49.7       16.7   
1711152000000     11.0      3.8   6.4           4      86.5       34.2   
1700524800000      8.8      3.7   6.5           5      71.1       28.7   
1715212800000     22.2     16.2  18.7           0      54.0       14.4   
...                ...      ...   ...         ...       ...        ...   
1712793600000     16.5     10.0  12.5           4      86.8       23.3   
1693526400000     25.5     17.8  21.4           0      51.1       21.5   
1701648000000     11.2      6.7   8.7           0      70.5       32.7   
1701734400000      6.7      4.3   5.7           2      57.4       14.2   
1693958400000     33.4     25.0  29.0           3      64.2        9.3   

               visibility  Distance to CMS  Distance to CHS  Distance to CIL  \
Issue Date                                                                     
1704153600000        15.9         0.624092         0.770406         0.694539   
1681084800000        15.9         0.599122         0.674377         0.539057   
1711152000000        10.9         0.618336         0.726699         0.613188   
1700524800000        15.3         0.596087         0.683229         0.547075   
1715212800000        16.0         0.616560         0.697509         0.577836   
...                   ...              ...              ...              ...   
1712793600000        14.1         0.621512         0.685835         0.558747   
1693526400000        15.9         0.590814         0.680176         0.528206   
1701648000000        16.0         0.600065         0.710330         0.588772   
1701734400000        16.0         0.587513         0.691421         0.588377   
1693958400000        15.5         0.597272         0.668268         0.522613   

               Distance to CIS  Distance to CB  Registration State  \
Issue Date                                                           
1704153600000         5.639707        0.116056                   0   
1681084800000         4.413902        0.101889                   0   
1711152000000         4.994734        0.109155                   0   
1700524800000         4.488524        0.099647                   0   
1715212800000         4.718427        0.108054                   0   
...                        ...             ...                 ...   
1712793600000         4.628527        0.108062                   0   
1693526400000         4.291356        0.099738                   0   
1701648000000         4.735504        0.104834                   0   
1701734400000         4.807496        0.103586                   0   
1693958400000         4.317040        0.099134                   0   

               Plate Type  Violation Code  Vehicle Body Type  Vehicle Make  \
Issue Date                                                                   
1704153600000           0               1                  0             1   
1681084800000           0               1                  0             1   
1711152000000           0               3                  0             1   
1700524800000           0               1                  0             0   
1715212800000           0               3                  0             0   
...                   ...             ...                ...           ...   
1712793600000           0               3                  0             0   
1693526400000           0               1                  0             0   
1701648000000           0               1                  0             1   
1701734400000           0               1                  0             0   
1693958400000           0               3                  0             0   

               Issuing Agency  Violation County  
Issue Date                         

Issue Date
1704153600000    1
1681084800000    1
1711152000000    0
1700524800000    1
1715212800000    1
                ..
1712793600000    1
1693526400000    1
1701648000000    1
1701734400000    1
1693958400000    1
Name: High Number of Tickets, Length: 562, dtype: int64

In [55]:
X_train_, y_train_ = X_train.values.persist(), y_train.values.persist()
X_test_, y_test_ = X_test.values.persist(), y_test.values.persist()

In [56]:
X_train_.compute_chunk_sizes(), y_train_.compute_chunk_sizes(), X_test_.compute_chunk_sizes(), y_test_.compute_chunk_sizes()

(dask.array<values, shape=(562, 19), dtype=float64, chunksize=(562, 19), chunktype=numpy.ndarray>,
 dask.array<values, shape=(562,), dtype=int64, chunksize=(562,), chunktype=numpy.ndarray>,
 dask.array<values, shape=(133, 19), dtype=float64, chunksize=(133, 19), chunktype=numpy.ndarray>,
 dask.array<values, shape=(133,), dtype=int64, chunksize=(133,), chunktype=numpy.ndarray>)

## Dask ML

In [57]:
from dask_ml.linear_model import LinearRegression, LogisticRegression

In [58]:
lr = LogisticRegression(solver_kwargs={"normalize":False})
lr.fit(X_train_, y_train_)

LogisticRegression(solver_kwargs={'normalize': False})

In [59]:
preds = lr.predict(X_test_)
preds_proba = lr.predict_proba(X_test_)

In [60]:
y_test_.compute(), preds.compute(), preds_proba.compute()

(array([1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
        0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
        1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1,
        0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
        1]),
 array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True, False,  True, False,  True,  True,  True,  True,
         True, False,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True, False,  True,  True,  True,  True,  True,
         True,  True,  True, False,  True,  True,  True,  True,  True,
         True, False,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  Tr

In [61]:
accuracy_score(y_test_, preds)

np.float64(0.6090225563909775)

In [62]:
log_loss(y_test_, preds_proba)

9.190047283839501

## XGBoost

In [63]:
import xgboost as xgb

In [64]:
clf = xgb.XGBClassifier(
    n_estimators=1000,
    max_depth=10,
    learning_rate=0.3,
    n_jobs=-1,
    random_state=42
)
clf.fit(X_train_, y_train_)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.3, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=10, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=1000, n_jobs=-1,
              num_parallel_tree=None, random_state=42, ...)

In [65]:
preds = clf.predict(X_test_)
preds_proba = clf.predict_proba(X_test_)

In [66]:
y_test_.compute(), preds, preds_proba

(array([1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
        0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
        1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1,
        0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
        1]),
 array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
        1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
        0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
        1]),
 array([[3.34143639e-04, 9.99665856e-01],
        [9.04690027e-02, 9.09530997e-01],
  

In [67]:
accuracy_score(y_test_, preds)

np.float64(0.924812030075188)

In [68]:
log_loss(y_test_, preds_proba)

0.17843953301917934

## Scikit

In [69]:
from sklearn.neural_network import MLPClassifier

In [70]:
batch_size = 10
X_batches = [X_train_[i:i+batch_size] for i in range(0, len(X_train_), batch_size)]
y_batches = [y_train_[i:i+batch_size] for i in range(0, len(y_train_), batch_size)]

In [72]:
clf = MLPClassifier(
        max_iter=1000,
        tol=1e-3,
        random_state=42,
        hidden_layer_sizes=(128, 256, 512, 256, 128),
)

for X_batch, y_batch in zip(X_batches, y_batches):
    clf.partial_fit(X_batch, y_batch, classes=[0, 1])

In [73]:
preds = clf.predict(X_test_)
preds_proba = clf.predict_proba(X_test_)

In [74]:
y_test_.compute(), preds, preds_proba

(array([1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
        0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
        1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1,
        0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
        1]),
 array([1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
        0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1,
        1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1,
        0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1,
        1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1,
        0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
        1]),
 array([[0.45557049, 0.54442951],
        [0.46148616, 0.53851384],
        [0.5028572

In [75]:
accuracy_score(y_test_, preds)

np.float64(0.5789473684210527)

In [76]:
log_loss(y_test_, preds_proba)

0.6817311679913799